"""Emit _motifs.svg, _preview.html and the 36 Growing Map figures for Level 4."""
import glob
import os
from _gen_core import *
from _gen_pat import PATTERNS, EXAMPLES, BY_ID
import _gen_map

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # figures/

PALETTE = [("data", DATA_S, DATA_F, "5.28:1", 108, 232),
           ("model", MODEL_S, MODEL_F, "7.10:1", 88, 212),
           ("human", HUMAN_S, HUMAN_F, "5.80:1", 101, 202),
           ("correct", OK_S, OK_F, "5.34:1", 107, 242),
           ("wrong", BAD_S, BAD_F, "5.34:1", 107, 192),
           ("accent", ACC_S, ACC_F, "5.16:1", 109, 222),
           ("ink", INK, None, "16.52:1", 31, None),
           ("paper", PAPER, None, "1.00:1", 255, None)]

GROUPS = [("Training and loss",
           ["motif-loss-curve", "motif-loss-compare", "motif-train-val-gap", "motif-coin-floor", "motif-lr-schedule"]),
          ("Sequences and attention",
           ["motif-token-stream", "motif-bpe-merge", "motif-attention-grid", "motif-causal-mask",
            "motif-attention-arcs", "motif-gradient-compound", "motif-tensor-2d", "motif-block-stack"]),
          ("Retrieval, agents and systems",
           ["motif-cosine-table", "motif-rag-flow", "motif-recall-at-k", "motif-agent-loop",
            "motif-cost-growth", "motif-fence", "motif-trace"]),
          ("Evaluation and honesty",
           ["motif-eval-table", "motif-ablation-table", "motif-stand-in-and-quoted"])]


def pattern_svg(p):
    return svg_doc(p["vb"], p["title"], p["desc"], p["body"])


def figure_files():
    return sorted(os.path.basename(f) for f in glob.glob(os.path.join(HERE, "fig-*.svg")))


def emit_maps():
    maps = _gen_map.build_maps()
    for name, svg in maps.items():
        open(os.path.join(HERE, name), "w").write(svg)
    return len(maps)


def emit_motifs():
    out = ['<?xml version="1.0" encoding="UTF-8"?>',
           '<!-- AI Academy - Level 4 (Innovator) - motif sprite sheet. GENERATED by _generator/_gen_build.py; do not edit.',
           '     Use:  <use href="_motifs.svg#motif-attention-grid" x="40" y="40" width="500" height="500" aria-label="..."/>',
           '     Or copy the contents of a <symbol> inline. Every motif is drawn to its own viewBox, origin top-left,',
           '     so translate(x,y) puts its top-left corner at exactly (x,y). Never place a motif at scale() below 1. -->',
           '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10" role="img" aria-hidden="true" style="display:none">',
           '  <title>AI Academy Level 4 motif sprite sheet</title>',
           '  <desc>A hidden library of reusable motif symbols for Level 4 figures: loss curves, token streams, attention '
           'grids, the transformer block, retrieval, agent loops, traces, evaluation tables and the stand-in and quoted chips.</desc>']
    for m in MOTIFS:
        out.append('  <!-- %s -->' % m["id"])
        out.append('  <symbol id="%s" viewBox="%s">' % (m["id"], m["vb"]))
        out.append('    <title>%s</title>' % m["title"])
        out.append('    <desc>%s</desc>' % m["desc"])
        out.append(m["body"])
        out.append('  </symbol>')
    out.append('</svg>')
    open(os.path.join(HERE, "_motifs.svg"), "w").write("\n".join(out) + "\n")


CSS = """  :root { --ink:#14202B; --mut:#55636F; --grid:#C7CDD4; --panel:#F5F8FA; }
  body { font-family:ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif; color:var(--ink); background:#fff; margin:0; padding:32px; line-height:1.5; }
  .wrap { max-width:1100px; margin:0 auto; }
  h1 { font-size:28px; margin:0 0 4px; } h2 { font-size:20px; margin:40px 0 12px; border-bottom:2px solid var(--grid); padding-bottom:6px; }
  h3 { font-size:15px; margin:0 0 4px; font-weight:600; } h3 span { color:var(--mut); font-weight:400; font-size:12px; }
  h4 { font-size:14px; margin:24px 0 8px; color:var(--mut); text-transform:uppercase; letter-spacing:.06em; }
  p.lead { color:var(--mut); margin:0 0 8px; }
  code { font-family:ui-monospace,SFMono-Regular,Menlo,monospace; font-size:12px; background:var(--panel); padding:1px 5px; border-radius:4px; }
  .bar { position:sticky; top:0; background:#fff; border-bottom:2px solid var(--grid); padding:10px 0; margin-bottom:8px; z-index:9; }
  .bar label { margin-right:20px; font-size:14px; cursor:pointer; }
  .swatches { display:grid; grid-template-columns:repeat(auto-fill,minmax(250px,1fr)); gap:10px; }
  .sw { display:grid; grid-template-columns:34px 1fr; gap:4px 10px; align-items:center; border:1.5px solid var(--grid); border-radius:8px; padding:10px; }
  .sw .chip { grid-row:1/4; width:34px; height:34px; border-radius:8px; border:3px solid; }
  .sw b { font-size:14px; } .sw span { font-size:11px; color:var(--mut); }
  .motifs { display:grid; grid-template-columns:repeat(auto-fill,minmax(330px,1fr)); gap:14px; }
  .motifs figure { margin:0; border:1.5px solid var(--grid); border-radius:10px; padding:10px; }
  .motifs svg { width:100%; height:260px; }
  figcaption { margin-top:6px; display:flex; flex-direction:column; gap:2px; }
  figcaption span { font-size:11px; color:var(--mut); }
  .pat { margin:0 0 26px; } .pat .frame { border:1.5px solid var(--grid); border-radius:10px; padding:8px; }
  .pat svg, .pat img { width:100%; height:auto; display:block; }
  p.note { font-size:12px; color:var(--mut); margin:0 0 8px; }
  .figs { display:grid; grid-template-columns:repeat(auto-fill,minmax(330px,1fr)); gap:14px; }
  .figs figure { margin:0; border:1.5px solid var(--grid); border-radius:10px; padding:8px; }
  .figs img { width:100%; height:auto; display:block; }
  body.grey { filter:grayscale(1); }
  body.dark { background:#20262c; }"""


def _fig(m):
    return ('<figure><svg viewBox="%s" role="img" aria-label="%s"><use href="#%s"/></svg>'
            '<figcaption><code>%s</code><span>%s</span><span>%s</span></figcaption></figure>'
            % (m["vb"], m["title"], m["id"], m["id"], m["vb"], m["note"]))


def emit_preview():
    o = ['<!DOCTYPE html>',
         '<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">',
         '<title>AI Academy - Level 4 figure style system</title>', '<style>', CSS, '</style></head>', '<body>']
    sprite = ['<svg xmlns="http://www.w3.org/2000/svg" style="display:none" aria-hidden="true">']
    for m in MOTIFS:
        sprite.append('<symbol id="%s" viewBox="%s"><title>%s</title><desc>%s</desc>%s</symbol>'
                      % (m["id"], m["vb"], m["title"], m["desc"], m["body"]))
    sprite.append('</svg>')
    o.append("".join(sprite))
    o += ['<div class="wrap">',
          '<h1>AI Academy &mdash; Level 4 (Innovator) figure style system</h1>',
          '<p class="lead">Generated by <code>_generator/_gen_build.py</code>. Same palette, strokes, type scale and '
          'accessibility rules as Levels 1&ndash;3, plus the Level 4 rules: seeded numbers only, stand-ins drawn as '
          'stand-ins, quoted is not measured, series told apart by more than colour, heatmap cells carry their value.</p>',
          '<div class="bar">',
          '  <label><input type="checkbox" onchange="document.body.classList.toggle(\'grey\',this.checked)"> Greyscale (print check)</label>',
          '  <label><input type="checkbox" onchange="document.body.classList.toggle(\'dark\',this.checked)"> Dark page (transparency check)</label>',
          '</div>',
          '<h2>Palette &mdash; inherited verbatim</h2>', '<div class="swatches">']
    for name, s, f, aa, gs, gf in PALETTE:
        o.append('<div class="sw"><div class="chip" style="background:%s;border-color:%s"></div>' % (f or s, s))
        extra = " &middot; fill grey %s" % gf if gf else ""
        o.append('<b>%s</b><code>%s</code><span>AA %s &middot; stroke grey %s%s</span>' % (name, s, aa, gs, extra))
        o.append('<code>%s</code></div>' % f if f else '</div>')
    o.append('</div>')
    o.append('<h2>Motifs (%d)</h2>' % len(MOTIFS))
    o.append('<p class="lead">Rendered through <code>&lt;use href="#motif-id"/&gt;</code> from the inlined sprite.</p>')
    seen = set()
    for gname, ids in GROUPS:
        o.append('<h4>%s</h4><div class="motifs">' % gname)
        for mid in ids:
            o.append(_fig(BY_ID[mid]))
            seen.add(mid)
        o.append('</div>')
    assert seen == set(BY_ID), "preview groups miss motifs: %s" % sorted(set(BY_ID) - seen)
    o.append('<h2>Composition patterns (%d)</h2>' % len(PATTERNS))
    for p in PATTERNS:
        w = p["vb"].split()[2]
        o.append('<section class="pat"><h3>%s <span>%s</span></h3><p class="note">%s</p>' % (p["id"], p["vb"], p["note"]))
        o.append('<div class="frame" style="max-width:%spx"><svg viewBox="%s" role="img"><title>%s</title><desc>%s</desc>\n%s\n</svg></div></section>'
                 % (w, p["vb"], p["title"], p["desc"], p["body"]))
    files = figure_files()
    o.append('<h2>Week figures (%d fig-*.svg files)</h2>' % len(files))
    o.append('<p class="lead">Every <code>fig-*.svg</code> in this folder, shown through <code>&lt;img&gt;</code>. '
             'Reload after running <code>python3 _gen_build.py</code>.</p><div class="figs">')
    for f in files:
        o.append('<figure><img src="%s" alt="%s"><figcaption><code>%s</code></figcaption></figure>' % (f, f, f))
    o.append('</div></div></body></html>')
    open(os.path.join(HERE, "_preview.html"), "w").write("\n".join(o) + "\n")
